[toolchain]
# Pin to a known-good nightly. If CI images don't have this exact build,
# bump to the latest nightly that still compiles your tree.
channel = "nightly-2025-09-08"
components = ["rust-src", "llvm-tools-preview", "clippy", "rustfmt"]
targets = ["x86_64-unknown-none", "aarch64-unknown-none"]
