version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: sis-kernel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./sis_kernel_rules.yml:/etc/prometheus/sis_kernel_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    networks:
      - sis-kernel-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: sis-kernel-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboard.json:/var/lib/grafana/dashboards/sis-kernel.json
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=sis-kernel-admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/sis-kernel.json
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - sis-kernel-monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: sis-kernel-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--cluster.advertise-address=0.0.0.0:9093'
    restart: unless-stopped
    networks:
      - sis-kernel-monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: sis-kernel-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - sis-kernel-monitoring

  # SIS Kernel Testing Metrics Exporter
  sis-kernel-exporter:
    build:
      context: .
      dockerfile: Dockerfile.metrics-exporter
    container_name: sis-kernel-metrics-exporter
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    volumes:
      - ../target/testing:/data/testing:ro
    environment:
      - METRICS_PORT=8080
      - PERFORMANCE_METRICS_PORT=8081
      - SECURITY_METRICS_PORT=8082
      - DISTRIBUTED_METRICS_PORT=8083
      - AI_METRICS_PORT=8084
      - QEMU_METRICS_PORT=8085
      - DATA_PATH=/data/testing
    restart: unless-stopped
    networks:
      - sis-kernel-monitoring

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  sis-kernel-monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16