//! Help content database for all shell commands
//!
//! This module contains comprehensive help information for all 105+ shell commands
//! organized by category with detailed explanations and robotics analogies.

use super::help::{Category, CommandHelp, SubcommandHelp, ParameterHelp};

/// All commands with their help information (105 commands total)
pub static ALL_COMMANDS: &[CommandHelp] = &[
    // ========================================================================
    // CORE SYSTEM COMMANDS (12 commands)
    // ========================================================================

    CommandHelp {
        name: "help",
        category: Category::CoreSystem,
        brief: "Show command help (help [command])",
        what_it_does: "Displays comprehensive help information for all shell commands or detailed help for a specific command.",
        use_case: "Use when you need to discover available commands, understand command syntax, or get detailed information about a specific command's functionality.",
        functionality: "Without arguments, displays all commands organized by category. With a command name, shows detailed help including description, use cases, examples, and related commands.",
        robotics_analogy: "Like a robot's operator manual - provides documentation for all available operations. Essential for both new operators and experienced users who need to reference specific command details.",
        os_level_explanation: "Shell built-in that accesses the command metadata database to display usage information. Implements command discovery and self-documentation for the interactive shell interface.",
        subcommands: &[],
        examples: &["help", "help agentsys", "help memctl"],
        see_also: &["version", "info"],
        feature: None,
    },

    CommandHelp {
        name: "version",
        category: Category::CoreSystem,
        brief: "Show kernel version and build information",
        what_it_does: "Displays the SIS kernel version number, build timestamp, and configuration details.",
        use_case: "Use to verify the kernel version during debugging, testing, or when reporting issues. Important for ensuring compatibility with external tools and determining available features.",
        functionality: "Outputs kernel version string, build configuration, enabled features, and compilation timestamp.",
        robotics_analogy: "Like checking the firmware version on a robot's control unit - essential for verifying which capabilities and bug fixes are present in the current system.",
        os_level_explanation: "Reads compile-time constants embedded in the kernel binary, including version strings, feature flags, and build metadata. Similar to `uname -a` in Unix systems.",
        subcommands: &[],
        examples: &["version"],
        see_also: &["info", "help"],
        feature: None,
    },

    CommandHelp {
        name: "info",
        category: Category::CoreSystem,
        brief: "Show kernel information",
        what_it_does: "Displays comprehensive system information including hardware configuration, memory layout, and kernel subsystem status.",
        use_case: "Use when you need to understand the current system configuration, verify hardware detection, or troubleshoot subsystem initialization issues.",
        functionality: "Queries various kernel subsystems and hardware registers to compile a comprehensive status report covering CPU, memory, devices, and enabled features.",
        robotics_analogy: "Like a robot's system diagnostics panel - provides a complete overview of all hardware components, their status, and operational parameters.",
        os_level_explanation: "Aggregates information from the device tree, memory management subsystem, driver registry, and system registers to provide a holistic view of kernel state.",
        subcommands: &[],
        examples: &["info"],
        see_also: &["version", "mem", "dtb", "board"],
        feature: None,
    },

    CommandHelp {
        name: "clear",
        category: Category::CoreSystem,
        brief: "Clear screen",
        what_it_does: "Clears the terminal screen by sending ANSI escape sequences.",
        use_case: "Use to clear cluttered output and start with a clean screen for better readability.",
        functionality: "Sends terminal control sequences to clear the screen and reset cursor position.",
        robotics_analogy: "Like resetting a robot's display panel - clears old status messages to show fresh information.",
        os_level_explanation: "Outputs ANSI/VT100 escape sequences to clear screen and home cursor.",
        subcommands: &[],
        examples: &["clear"],
        see_also: &[],
        feature: None,
    },

    CommandHelp {
        name: "echo",
        category: Category::CoreSystem,
        brief: "Echo text to output",
        what_it_does: "Prints the provided text arguments to the console output.",
        use_case: "Use for basic output testing, debugging shell command parsing, or creating simple test scripts.",
        functionality: "Concatenates all arguments with spaces and outputs them to the console.",
        robotics_analogy: "Like a robot's status announcement system - confirms that the communication channel is working and messages are being transmitted correctly.",
        os_level_explanation: "Simple output command that demonstrates UART/console I/O functionality.",
        subcommands: &[],
        examples: &["echo Hello World", "echo Testing 123"],
        see_also: &["help", "info"],
        feature: None,
    },

    CommandHelp {
        name: "exit",
        category: Category::CoreSystem,
        brief: "Exit shell",
        what_it_does: "Exits the interactive shell and returns to the kernel's default execution mode.",
        use_case: "Use when you're done with interactive testing and want to return control to the kernel or halt the system.",
        functionality: "Terminates the shell loop and returns to the caller.",
        robotics_analogy: "Like shutting down a robot's manual control interface to return to autonomous operation mode.",
        os_level_explanation: "Sets the shell's running flag to false, causing the command loop to terminate.",
        subcommands: &[],
        examples: &["exit"],
        see_also: &[],
        feature: None,
    },

    CommandHelp {
        name: "mem",
        category: Category::CoreSystem,
        brief: "Show memory information",
        what_it_does: "Displays detailed memory subsystem information including allocator stats and heap usage.",
        use_case: "Use to monitor memory consumption, detect memory leaks, or verify heap allocator behavior.",
        functionality: "Queries the buddy allocator and heap to gather statistics on allocated/free memory.",
        robotics_analogy: "Like checking a robot's RAM usage - essential for ensuring the system has sufficient memory.",
        os_level_explanation: "Reads kernel allocator metadata to display heap statistics and buddy allocator state.",
        subcommands: &[],
        examples: &["mem"],
        see_also: &["memctl", "info"],
        feature: None,
    },

    CommandHelp {
        name: "regs",
        category: Category::CoreSystem,
        brief: "Show system registers",
        what_it_does: "Displays ARM system registers including EL, MPIDR, SCTLR, and other control registers.",
        use_case: "Use for low-level debugging, verifying CPU state, or understanding exception level configuration.",
        functionality: "Reads and displays ARM architectural registers and system control registers.",
        robotics_analogy: "Like reading a robot's internal control registers - shows the processor's current state and configuration.",
        os_level_explanation: "Executes MRS instructions to read ARM system registers including exception level, MMU config, and cache settings.",
        subcommands: &[],
        examples: &["regs"],
        see_also: &["info", "dtb"],
        feature: None,
    },

    CommandHelp {
        name: "dtb",
        category: Category::CoreSystem,
        brief: "Show device tree information",
        what_it_does: "Displays device tree blob information including node structure and properties.",
        use_case: "Use to verify device tree parsing, check hardware configuration, or debug device detection issues.",
        functionality: "Parses and displays the device tree structure passed by the bootloader.",
        robotics_analogy: "Like reading a robot's hardware manifest - describes all connected devices and their configuration.",
        os_level_explanation: "Parses the DTB (Device Tree Blob) passed by UEFI/bootloader to enumerate hardware topology.",
        subcommands: &[],
        examples: &["dtb"],
        see_also: &["info", "board"],
        feature: None,
    },

    CommandHelp {
        name: "vector",
        category: Category::CoreSystem,
        brief: "Show vector extension information",
        what_it_does: "Displays ARM NEON/SVE vector extension availability and configuration.",
        use_case: "Use to verify SIMD capabilities for AI/ML workloads or vector-accelerated operations.",
        functionality: "Checks CPU features for NEON, SVE, and other vector extensions.",
        robotics_analogy: "Like checking if a robot's processor has accelerated math hardware for sensor fusion and navigation.",
        os_level_explanation: "Reads CPU feature registers to detect NEON/SVE support for SIMD operations.",
        subcommands: &[],
        examples: &["vector"],
        see_also: &["info", "regs"],
        feature: None,
    },

    CommandHelp {
        name: "board",
        category: Category::CoreSystem,
        brief: "Show board-specific information",
        what_it_does: "Displays platform-specific information including board model and revision.",
        use_case: "Use to identify the exact hardware platform for compatibility checking.",
        functionality: "Reads board identification registers and device tree compatible strings.",
        robotics_analogy: "Like reading a robot's model number and hardware revision - identifies the exact platform variant.",
        os_level_explanation: "Queries device tree and platform registers to identify board model and configuration.",
        subcommands: &[],
        examples: &["board"],
        see_also: &["info", "dtb"],
        feature: None,
    },

    CommandHelp {
        name: "verify",
        category: Category::CoreSystem,
        brief: "Run comprehensive verification tests",
        what_it_does: "Executes property-based and metamorphic verification tests for kernel correctness.",
        use_case: "Use to verify kernel correctness, test invariants, or validate subsystem behavior.",
        functionality: "Runs property-based testing, metamorphic testing, and verification checks.",
        robotics_analogy: "Like running a robot's self-diagnostics - verifies all systems are operating correctly.",
        os_level_explanation: "Executes comprehensive test suite including property-based tests and invariant checks.",
        subcommands: &[],
        examples: &["verify"],
        see_also: &["test", "validate"],
        feature: None,
    },

    // ========================================================================
    // FILESYSTEM COMMANDS (3 commands)
    // ========================================================================

    CommandHelp {
        name: "ls",
        category: Category::Filesystem,
        brief: "List directory contents",
        what_it_does: "Lists files and directories in the specified path.",
        use_case: "Use to explore the VFS structure or navigate the filesystem during testing.",
        functionality: "Opens the specified directory through VFS and enumerates all entries.",
        robotics_analogy: "Like a robot surveying its environment - identifies all objects and locations in a given area.",
        os_level_explanation: "Performs VFS open() and readdir() syscalls to enumerate directory entries.",
        subcommands: &[],
        examples: &["ls", "ls /tmp", "ls /dev"],
        see_also: &["cat", "blkctl"],
        feature: None,
    },

    CommandHelp {
        name: "cat",
        category: Category::Filesystem,
        brief: "Print file contents (first 4KB)",
        what_it_does: "Reads and displays the contents of a file.",
        use_case: "Use to inspect file contents or verify file writes.",
        functionality: "Opens the file through VFS and reads up to 4KB.",
        robotics_analogy: "Like a robot reading a configuration file - retrieves stored information for inspection.",
        os_level_explanation: "Executes VFS open() and read() syscalls to fetch file data.",
        subcommands: &[],
        examples: &["cat /etc/config.txt", "cat /tmp/test.log"],
        see_also: &["ls", "blkctl"],
        feature: None,
    },

    CommandHelp {
        name: "blkctl",
        category: Category::Filesystem,
        brief: "Block device control",
        what_it_does: "Lists and provides information about block storage devices.",
        use_case: "Use to discover available storage devices or troubleshoot storage issues.",
        functionality: "Queries the block device layer to enumerate registered devices.",
        robotics_analogy: "Like listing a robot's storage compartments - shows all available data storage units.",
        os_level_explanation: "Interfaces with the kernel's block device subsystem to enumerate devices.",
        subcommands: &[
            SubcommandHelp {
                name: "list",
                brief: "List all block devices",
                usage: "blkctl list",
                parameters: &[],
                example: "blkctl list",
            },
        ],
        examples: &["blkctl list"],
        see_also: &["ls", "cat"],
        feature: None,
    },

    // ========================================================================
    // MEMORY MANAGEMENT COMMANDS (1 command)
    // ========================================================================

    CommandHelp {
        name: "memctl",
        category: Category::MemoryManagement,
        brief: "Memory neural agent control (AI-driven allocation prediction)",
        what_it_does: "Controls the AI-driven memory management agent that predicts allocation patterns.",
        use_case: "Use to enable AI-driven memory prediction or test neural memory management.",
        functionality: "Manages the neural agent that learns memory allocation patterns.",
        robotics_analogy: "Like a robot's resource manager that learns usage patterns - predicts when more memory will be needed.",
        os_level_explanation: "Controls the Phase 2 neural memory agent which uses ML models to predict allocation patterns.",
        subcommands: &[
            SubcommandHelp {
                name: "status",
                brief: "Show memory agent status",
                usage: "memctl status",
                parameters: &[],
                example: "memctl status",
            },
            SubcommandHelp {
                name: "predict",
                brief: "Run memory allocation prediction",
                usage: "memctl predict",
                parameters: &[],
                example: "memctl predict",
            },
            SubcommandHelp {
                name: "stress",
                brief: "Run memory stress test",
                usage: "memctl stress [allocations]",
                parameters: &[],
                example: "memctl stress 500",
            },
        ],
        examples: &["memctl status", "memctl predict", "memctl stress 1000"],
        see_also: &["mem", "autoctl", "neuralctl"],
        feature: None,
    },

    // ========================================================================
    // NETWORK COMMANDS (2 commands)
    // ========================================================================

    CommandHelp {
        name: "netctl",
        category: Category::Network,
        brief: "Network neural agent control",
        what_it_does: "Controls network prediction and buffer management using AI.",
        use_case: "Use to optimize network performance with AI-driven predictions.",
        functionality: "Manages neural network agent for traffic prediction and buffer optimization.",
        robotics_analogy: "Like a robot's communication optimizer - predicts network usage and adjusts buffers accordingly.",
        os_level_explanation: "Controls Phase 2 network neural agent for traffic pattern prediction and buffer sizing.",
        subcommands: &[],
        examples: &["netctl predict", "netctl buffers"],
        see_also: &["webctl", "metrics"],
        feature: None,
    },

    CommandHelp {
        name: "webctl",
        category: Category::Network,
        brief: "Web server and WebSocket control",
        what_it_does: "Manages embedded HTTP server and WebSocket connections.",
        use_case: "Use to enable web-based monitoring and control interfaces.",
        functionality: "Controls web server, WebSocket connections, and API endpoints.",
        robotics_analogy: "Like a robot's remote control interface - enables web-based monitoring and commands.",
        os_level_explanation: "Manages embedded HTTP/WebSocket server for remote monitoring and control.",
        subcommands: &[],
        examples: &["webctl start", "webctl status", "webctl ws-status"],
        see_also: &["netctl", "metrics"],
        feature: None,
    },

    // ========================================================================
    // AGENT SUPERVISION (ASM) COMMANDS (7 commands)
    // ========================================================================

    CommandHelp {
        name: "agentsys",
        category: Category::AgentSupervision,
        brief: "Agent Supervision Module (ASM) control and monitoring",
        what_it_does: "Provides comprehensive control and monitoring of the Agent Supervision Module.",
        use_case: "Use to monitor agent status, collect telemetry, verify compliance, manage resources, and track dependencies.",
        functionality: "Interfaces with all 8 ASM subsystems: Agent Supervisor, Telemetry Aggregator, Fault Detector, Policy Controller, Compliance Tracker, Resource Monitor, Dependency Graph, and System Profiler.",
        robotics_analogy: "Like a robot's central monitoring system - oversees all subsystems, collects diagnostics, enforces safety policies.",
        os_level_explanation: "Manages kernel's agent supervision infrastructure with lifecycle management, telemetry, compliance tracking, and resource limits.",
        subcommands: &[
            SubcommandHelp {
                name: "status",
                brief: "Show ASM system status",
                usage: "agentsys status",
                parameters: &[],
                example: "agentsys status",
            },
            SubcommandHelp {
                name: "list",
                brief: "List all active agents",
                usage: "agentsys list",
                parameters: &[],
                example: "agentsys list",
            },
            SubcommandHelp {
                name: "spawn",
                brief: "Spawn a test agent",
                usage: "agentsys spawn <id> <name> <capabilities>",
                parameters: &[
                    ParameterHelp {
                        name: "id",
                        param_type: "u32",
                        required: true,
                        description: "Unique agent ID",
                    },
                ],
                example: "agentsys spawn 100 test_agent FsBasic",
            },
        ],
        examples: &["agentsys status", "agentsys list", "agentsys spawn 100 test FsBasic"],
        see_also: &["asmstatus", "agentctl", "coordctl"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "asmstatus",
        category: Category::AgentSupervision,
        brief: "ASM telemetry snapshot (legacy)",
        what_it_does: "Shows Agent Supervision Module telemetry snapshot.",
        use_case: "Legacy command for quick ASM status check.",
        functionality: "Displays ASM system telemetry and subsystem status.",
        robotics_analogy: "Like a quick-check dashboard on a robot showing all system health indicators.",
        os_level_explanation: "Legacy wrapper for ASM status display, maintained for backward compatibility.",
        subcommands: &[],
        examples: &["asmstatus"],
        see_also: &["agentsys"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "asmlist",
        category: Category::AgentSupervision,
        brief: "List active agents (legacy)",
        what_it_does: "Lists all active agents in the system.",
        use_case: "Legacy command for agent enumeration.",
        functionality: "Displays active agent list with basic information.",
        robotics_analogy: "Like listing all active processes in a robot's control system.",
        os_level_explanation: "Legacy wrapper for agent listing functionality.",
        subcommands: &[],
        examples: &["asmlist"],
        see_also: &["agentsys list"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "asminfo",
        category: Category::AgentSupervision,
        brief: "ASM detailed information (legacy)",
        what_it_does: "Shows detailed ASM subsystem information.",
        use_case: "Legacy command for ASM diagnostics.",
        functionality: "Displays comprehensive ASM subsystem details.",
        robotics_analogy: "Like detailed system diagnostics for robot supervision subsystems.",
        os_level_explanation: "Legacy wrapper providing detailed ASM information.",
        subcommands: &[],
        examples: &["asminfo"],
        see_also: &["agentsys status"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "asmpolicy",
        category: Category::AgentSupervision,
        brief: "ASM policy information (legacy)",
        what_it_does: "Shows ASM policy controller status and rules.",
        use_case: "Legacy command for policy inspection.",
        functionality: "Displays active policies and enforcement rules.",
        robotics_analogy: "Like viewing a robot's safety rules and operational constraints.",
        os_level_explanation: "Legacy wrapper for policy controller information.",
        subcommands: &[],
        examples: &["asmpolicy"],
        see_also: &["agentsys policy"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "gwstatus",
        category: Category::AgentSupervision,
        brief: "Cloud gateway status",
        what_it_does: "Shows cloud gateway connection status and routing information.",
        use_case: "Use to verify cloud connectivity for LLM routing and agent communication.",
        functionality: "Displays gateway status, active connections, and routing tables.",
        robotics_analogy: "Like checking a robot's connection to cloud services for remote AI processing.",
        os_level_explanation: "Shows ASM cloud gateway subsystem status for LLM provider routing.",
        subcommands: &[],
        examples: &["gwstatus"],
        see_also: &["agentsys gwstatus"],
        feature: Some("agentsys"),
    },

    CommandHelp {
        name: "agentctl",
        category: Category::AgentSupervision,
        brief: "Agent message bus control",
        what_it_does: "Controls the agent message bus for inter-agent communication.",
        use_case: "Use to monitor agent communication patterns and message statistics.",
        functionality: "Manages message bus, shows statistics, and provides diagnostics.",
        robotics_analogy: "Like monitoring the communication bus between robot subsystems.",
        os_level_explanation: "Controls Phase 1 agent message bus for inter-agent coordination.",
        subcommands: &[],
        examples: &["agentctl bus", "agentctl stats"],
        see_also: &["coordctl", "agentsys"],
        feature: None,
    },

    // ========================================================================
    // AI PHASE 1 COMMANDS (9 commands)
    // ========================================================================

    CommandHelp {
        name: "neuralctl",
        category: Category::AiPhase1,
        brief: "Neural agent control",
        what_it_does: "Controls the neural agent for autonomous system optimization.",
        use_case: "Use to enable AI-driven system optimization and learning.",
        functionality: "Manages neural agent training, inference, and autonomous operation.",
        robotics_analogy: "Like a robot's learning brain - continuously improves performance through experience.",
        os_level_explanation: "Controls Phase 1 neural agent with online learning and autonomous decision making.",
        subcommands: &[],
        examples: &["neuralctl status", "neuralctl autonomous on"],
        see_also: &["autoctl", "learnctl"],
        feature: None,
    },

    CommandHelp {
        name: "autoctl",
        category: Category::AiPhase1,
        brief: "Autonomous control system",
        what_it_does: "Controls the autonomous agent that makes system-wide optimization decisions.",
        use_case: "Use to enable autonomous operation with AI-driven decision making.",
        functionality: "Manages autonomous agent lifecycle, decision phases, and safety limits.",
        robotics_analogy: "Like enabling a robot's autonomous mode - the system makes decisions without human intervention.",
        os_level_explanation: "Phase 1 autonomous agent with 4-phase decision pipeline and safety constraints.",
        subcommands: &[],
        examples: &["autoctl on", "autoctl status", "autoctl dashboard"],
        see_also: &["neuralctl", "learnctl"],
        feature: None,
    },

    CommandHelp {
        name: "learnctl",
        category: Category::AiPhase1,
        brief: "Prediction tracking and feedback",
        what_it_does: "Manages prediction tracking and provides feedback for learning systems.",
        use_case: "Use to track prediction accuracy and improve learning models.",
        functionality: "Collects prediction statistics and processes feedback for model improvement.",
        robotics_analogy: "Like a robot's performance tracker - learns from mistakes to improve future decisions.",
        os_level_explanation: "Phase 1 learning subsystem for prediction tracking and feedback processing.",
        subcommands: &[],
        examples: &["learnctl stats", "learnctl feedback good 1"],
        see_also: &["neuralctl", "autoctl"],
        feature: None,
    },

    CommandHelp {
        name: "schedctl",
        category: Category::AiPhase1,
        brief: "Scheduling control",
        what_it_does: "Controls CPU scheduling with AI-driven optimizations.",
        use_case: "Use to configure scheduling policies and enable AI-driven scheduling.",
        functionality: "Manages workload priorities, CPU affinity, and shadow scheduling.",
        robotics_analogy: "Like a robot's task scheduler - decides which operations run when for optimal performance.",
        os_level_explanation: "Phase 1 scheduler control with shadow mode for A/B testing scheduling policies.",
        subcommands: &[],
        examples: &["schedctl workload", "schedctl shadow on"],
        see_also: &["autoctl", "det"],
        feature: None,
    },

    CommandHelp {
        name: "cmdctl",
        category: Category::AiPhase1,
        brief: "Command prediction",
        what_it_does: "Predicts likely next commands based on usage patterns.",
        use_case: "Use to test command prediction or pre-warm command paths.",
        functionality: "Analyzes command history to predict and prefetch next commands.",
        robotics_analogy: "Like a robot anticipating the next operator command based on typical workflows.",
        os_level_explanation: "Phase 1 command predictor using pattern recognition on shell history.",
        subcommands: &[],
        examples: &["cmdctl predict", "cmdctl batch"],
        see_also: &["neuralctl", "autoctl"],
        feature: None,
    },

    CommandHelp {
        name: "crashctl",
        category: Category::AiPhase1,
        brief: "Crash prediction and prevention",
        what_it_does: "Predicts and prevents system crashes using AI.",
        use_case: "Use to monitor crash risk and tune crash prevention thresholds.",
        functionality: "Analyzes system state to predict crashes and trigger preventive actions.",
        robotics_analogy: "Like a robot's safety system predicting failures before they happen.",
        os_level_explanation: "Phase 1 crash predictor using anomaly detection on system metrics.",
        subcommands: &[],
        examples: &["crashctl status", "crashctl history"],
        see_also: &["autoctl", "validate"],
        feature: None,
    },

    CommandHelp {
        name: "ask-ai",
        category: Category::AiPhase1,
        brief: "Ask AI a question",
        what_it_does: "Routes natural language questions to appropriate AI subsystems.",
        use_case: "Use to interact with AI systems using natural language queries.",
        functionality: "Parses questions and routes to relevant neural agents for answers.",
        robotics_analogy: "Like asking a robot a question and having it figure out which subsystem should answer.",
        os_level_explanation: "Phase 1 NLP interface mapping questions to agent capabilities.",
        subcommands: &[],
        examples: &["ask-ai \"What is system load?\""],
        see_also: &["neuralctl", "autoctl"],
        feature: None,
    },

    CommandHelp {
        name: "nnjson",
        category: Category::AiPhase1,
        brief: "Neural audit ring as JSON",
        what_it_does: "Exports neural agent audit log in JSON format.",
        use_case: "Use for automated analysis of neural agent decisions and actions.",
        functionality: "Serializes neural audit ring to JSON for external processing.",
        robotics_analogy: "Like exporting a robot's decision log for post-mission analysis.",
        os_level_explanation: "Phase 1 audit export for neural agent decision tracking.",
        subcommands: &[],
        examples: &["nnjson"],
        see_also: &["neuralctl", "autoctl audit"],
        feature: None,
    },

    CommandHelp {
        name: "nnact",
        category: Category::AiPhase1,
        brief: "Log neural action",
        what_it_does: "Logs a neural agent action for testing and debugging.",
        use_case: "Use to manually inject actions into neural audit log for testing.",
        functionality: "Records an action event in the neural audit ring.",
        robotics_analogy: "Like manually recording a robot action for training data collection.",
        os_level_explanation: "Phase 1 test utility for neural audit ring injection.",
        subcommands: &[],
        examples: &["nnact 1000"],
        see_also: &["neuralctl", "nnjson"],
        feature: None,
    },

    // ========================================================================
    // AI PHASE 2 COMMANDS (7 commands)
    // ========================================================================

    CommandHelp {
        name: "coordctl",
        category: Category::AiPhase2,
        brief: "Agent coordination control",
        what_it_does: "Manages multi-agent coordination and conflict resolution.",
        use_case: "Use to monitor agent interactions and resolve conflicts.",
        functionality: "Tracks agent dependencies, detects conflicts, and coordinates actions.",
        robotics_analogy: "Like coordinating multiple robot arms to avoid collisions while working together.",
        os_level_explanation: "Phase 2 multi-agent coordinator with conflict detection and resolution.",
        subcommands: &[],
        examples: &["coordctl status", "coordctl process"],
        see_also: &["agentctl", "metaclassctl"],
        feature: None,
    },

    CommandHelp {
        name: "deployctl",
        category: Category::AiPhase2,
        brief: "Deployment orchestration",
        what_it_does: "Controls gradual rollout and deployment of system changes.",
        use_case: "Use to manage staged deployments with rollback capability.",
        functionality: "Orchestrates deployment stages with health checks and rollback.",
        robotics_analogy: "Like gradually updating robot firmware across a fleet with automatic rollback on failure.",
        os_level_explanation: "Phase 2 deployment manager with canary releases and health monitoring.",
        subcommands: &[],
        examples: &["deployctl status", "deployctl advance"],
        see_also: &["versionctl", "shadowctl"],
        feature: None,
    },

    CommandHelp {
        name: "driftctl",
        category: Category::AiPhase2,
        brief: "Model drift detection",
        what_it_does: "Detects and handles ML model drift over time.",
        use_case: "Use to monitor model performance degradation and trigger retraining.",
        functionality: "Tracks model accuracy metrics and detects distribution drift.",
        robotics_analogy: "Like monitoring if a robot's learned behaviors are becoming less effective over time.",
        os_level_explanation: "Phase 2 drift detector monitoring model accuracy and data distribution changes.",
        subcommands: &[],
        examples: &["driftctl status", "driftctl retrain"],
        see_also: &["mlctl", "autoctl"],
        feature: None,
    },

    CommandHelp {
        name: "versionctl",
        category: Category::AiPhase2,
        brief: "Version control for models",
        what_it_does: "Manages versioning of ML models and configurations.",
        use_case: "Use to track model versions and rollback to previous versions.",
        functionality: "Implements version control for model weights and hyperparameters.",
        robotics_analogy: "Like keeping a history of robot control algorithm versions for comparison.",
        os_level_explanation: "Phase 2 version control system for ML models with diff and tagging.",
        subcommands: &[],
        examples: &["versionctl list", "versionctl commit", "versionctl rollback"],
        see_also: &["modelctl", "deployctl"],
        feature: None,
    },

    CommandHelp {
        name: "metaclassctl",
        category: Category::AiPhase2,
        brief: "Meta-agent control",
        what_it_does: "Controls the meta-agent that coordinates other agents.",
        use_case: "Use to enable hierarchical multi-agent control.",
        functionality: "Manages meta-agent that monitors and coordinates other AI agents.",
        robotics_analogy: "Like a supervisor robot overseeing and coordinating worker robots.",
        os_level_explanation: "Phase 2 meta-agent providing hierarchical agent management.",
        subcommands: &[],
        examples: &["metaclassctl status", "metaclassctl on"],
        see_also: &["coordctl", "autoctl"],
        feature: None,
    },

    CommandHelp {
        name: "mlctl",
        category: Category::AiPhase2,
        brief: "Advanced ML features",
        what_it_does: "Controls advanced ML features like experience replay and TD learning.",
        use_case: "Use to configure advanced learning algorithms and topologies.",
        functionality: "Manages experience replay, temporal difference learning, and topology adaptation.",
        robotics_analogy: "Like configuring a robot's advanced learning modes - learning from past experiences and predicting future states.",
        os_level_explanation: "Phase 2 advanced ML subsystem with experience replay and TD learning.",
        subcommands: &[],
        examples: &["mlctl status", "mlctl replay 100", "mlctl features"],
        see_also: &["actorctl", "neuralctl"],
        feature: None,
    },

    CommandHelp {
        name: "actorctl",
        category: Category::AiPhase2,
        brief: "Actor-critic control",
        what_it_does: "Controls actor-critic reinforcement learning with policy gradients.",
        use_case: "Use to configure advanced RL algorithms for continuous control.",
        functionality: "Manages actor-critic learning with eligibility traces and natural policy gradients.",
        robotics_analogy: "Like training a robot with both a 'doer' (actor) and a 'critic' that evaluates actions.",
        os_level_explanation: "Phase 2 actor-critic RL with policy gradients and KL divergence constraints.",
        subcommands: &[],
        examples: &["actorctl status", "actorctl policy", "actorctl lambda 0.9"],
        see_also: &["mlctl", "autoctl"],
        feature: None,
    },

    // ========================================================================
    // AI PHASE 7 COMMANDS (3 commands)
    // ========================================================================

    CommandHelp {
        name: "modelctl",
        category: Category::AiPhase7,
        brief: "Model lifecycle management",
        what_it_does: "Manages ML model lifecycle including loading, swapping, and health monitoring.",
        use_case: "Use for A/B testing models and safe model updates.",
        functionality: "Provides model versioning, hot-swapping, and rollback capabilities.",
        robotics_analogy: "Like swapping robot control algorithms on the fly while ensuring system stability.",
        os_level_explanation: "Phase 7 model lifecycle manager with version control and health checks.",
        subcommands: &[],
        examples: &["modelctl list", "modelctl swap v2", "modelctl rollback"],
        see_also: &["versionctl", "shadowctl"],
        feature: Some("model-lifecycle"),
    },

    CommandHelp {
        name: "tracectl",
        category: Category::AiPhase7,
        brief: "Decision trace management",
        what_it_does: "Manages decision traces for explainability and debugging.",
        use_case: "Use to understand AI decisions and detect divergences.",
        functionality: "Records, queries, and exports decision traces with full context.",
        robotics_analogy: "Like a robot's black box recorder showing why it made each decision.",
        os_level_explanation: "Phase 7 decision trace system for AI explainability and audit.",
        subcommands: &[],
        examples: &["tracectl list", "tracectl show 123", "tracectl export"],
        see_also: &["shadowctl", "autoctl audit"],
        feature: Some("decision-traces"),
    },

    CommandHelp {
        name: "shadowctl",
        category: Category::AiPhase7,
        brief: "Shadow mode and canary deployments",
        what_it_does: "Enables shadow mode for A/B testing and canary deployments.",
        use_case: "Use to safely test new models alongside production models.",
        functionality: "Runs shadow models in parallel, compares results, enables gradual rollout.",
        robotics_analogy: "Like testing new robot behaviors in simulation before deploying to real hardware.",
        os_level_explanation: "Phase 7 shadow execution for safe model A/B testing with canary deployment.",
        subcommands: &[],
        examples: &["shadowctl enable v2", "shadowctl stats", "shadowctl promote"],
        see_also: &["modelctl", "deployctl"],
        feature: Some("shadow-mode"),
    },

    // ========================================================================
    // LLM COMMANDS (13 commands)
    // ========================================================================

    CommandHelp {
        name: "llmctl",
        category: Category::Llm,
        brief: "LLM service control",
        what_it_does: "Manages LLM service configuration including model loading and budgets.",
        use_case: "Use to load AI models, configure real-time constraints, or audit LLM usage.",
        functionality: "Provides LLM lifecycle management with WCET budgets and verification.",
        robotics_analogy: "Like configuring a robot's AI reasoning engine with safety limits.",
        os_level_explanation: "Manages LLM service with WCET-based scheduling and cryptographic verification.",
        subcommands: &[],
        examples: &["llmctl load --wcet-cycles 500000", "llmctl status"],
        see_also: &["llminfer", "llmverify"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llminfer",
        category: Category::Llm,
        brief: "Submit LLM inference prompt",
        what_it_does: "Submits a text prompt to the LLM service for inference.",
        use_case: "Use to test LLM functionality or generate AI responses.",
        functionality: "Queues inference requests with deterministic scheduling.",
        robotics_analogy: "Like asking a robot's AI to solve a problem using its trained knowledge.",
        os_level_explanation: "Submits prompts to LLM inference engine with WCET constraints.",
        subcommands: &[],
        examples: &["llminfer What is a kernel?"],
        see_also: &["llmctl", "llmstream"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmstats",
        category: Category::Llm,
        brief: "LLM service statistics",
        what_it_does: "Shows LLM service usage statistics and performance metrics.",
        use_case: "Use to monitor LLM performance and resource usage.",
        functionality: "Displays inference counts, token statistics, and timing metrics.",
        robotics_analogy: "Like viewing a robot's AI usage statistics and performance metrics.",
        os_level_explanation: "Queries LLM service for runtime statistics and performance data.",
        subcommands: &[],
        examples: &["llmstats"],
        see_also: &["llmctl", "llmsummary"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmstream",
        category: Category::Llm,
        brief: "Stream LLM tokens",
        what_it_does: "Streams LLM output tokens in chunks for real-time display.",
        use_case: "Use to display LLM responses progressively as they're generated.",
        functionality: "Enables streaming token output with configurable chunk sizes.",
        robotics_analogy: "Like watching a robot's thoughts appear in real-time as it thinks.",
        os_level_explanation: "Streams LLM tokens via callback mechanism for incremental display.",
        subcommands: &[],
        examples: &["llmstream Explain memory allocation"],
        see_also: &["llminfer", "llmpoll"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmgraph",
        category: Category::Llm,
        brief: "Graph-backed LLM tokenization",
        what_it_does: "Uses graph infrastructure for LLM tokenization and processing.",
        use_case: "Use to test graph-based LLM pipeline integration.",
        functionality: "Processes text through graph operators for tokenization.",
        robotics_analogy: "Like routing robot sensor data through a processing pipeline.",
        os_level_explanation: "Integrates LLM with graph subsystem using SPSC channels.",
        subcommands: &[],
        examples: &["llmgraph Test tokenization"],
        see_also: &["graphctl", "llminfer"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmjson",
        category: Category::Llm,
        brief: "LLM audit log as JSON",
        what_it_does: "Exports LLM audit log in JSON format for compliance.",
        use_case: "Use for EU AI Act compliance and audit trail analysis.",
        functionality: "Serializes LLM audit events to JSON for external processing.",
        robotics_analogy: "Like exporting a robot's AI decision log for regulatory compliance.",
        os_level_explanation: "Exports LLM audit ring in JSON format for compliance tracking.",
        subcommands: &[],
        examples: &["llmjson"],
        see_also: &["llmctl audit", "compliance"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmsig",
        category: Category::Llm,
        brief: "Print model signature",
        what_it_does: "Displays cryptographic signature for a model ID.",
        use_case: "Use to verify model authenticity and integrity.",
        functionality: "Shows Ed25519 signature for model verification.",
        robotics_analogy: "Like checking a robot firmware's digital signature for authenticity.",
        os_level_explanation: "Displays model cryptographic signature for integrity verification.",
        subcommands: &[],
        examples: &["llmsig 1"],
        see_also: &["llmverify", "llmkey"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmpoll",
        category: Category::Llm,
        brief: "Poll inference tokens",
        what_it_does: "Polls for available tokens from last inference request.",
        use_case: "Use to retrieve inference results asynchronously.",
        functionality: "Retrieves generated tokens from LLM inference queue.",
        robotics_analogy: "Like checking if a robot's AI has finished thinking and has results ready.",
        os_level_explanation: "Polls LLM service for completed inference tokens.",
        subcommands: &[],
        examples: &["llmpoll", "llmpoll 50"],
        see_also: &["llminfer", "llmstream"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmcancel",
        category: Category::Llm,
        brief: "Cancel inference request",
        what_it_does: "Cancels a pending or running inference request.",
        use_case: "Use to stop long-running inferences or clear queue.",
        functionality: "Aborts inference by request ID or cancels all pending.",
        robotics_analogy: "Like telling a robot to stop thinking about a task and move on.",
        os_level_explanation: "Cancels LLM inference requests by ID or clears queue.",
        subcommands: &[],
        examples: &["llmcancel", "llmcancel 123"],
        see_also: &["llminfer", "llmpoll"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmsummary",
        category: Category::Llm,
        brief: "List recent LLM sessions",
        what_it_does: "Lists recent LLM inference sessions with token counts.",
        use_case: "Use to review recent LLM usage and completion status.",
        functionality: "Displays session IDs, token counts, and completion status.",
        robotics_analogy: "Like viewing a log of recent questions asked to a robot's AI.",
        os_level_explanation: "Queries LLM service for recent session summaries.",
        subcommands: &[],
        examples: &["llmsummary"],
        see_also: &["llmstats", "llmjson"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmverify",
        category: Category::Llm,
        brief: "Verify model package",
        what_it_does: "Verifies model package integrity using SHA-256 and Ed25519.",
        use_case: "Use to ensure model hasn't been tampered with before loading.",
        functionality: "Validates model hash and cryptographic signature.",
        robotics_analogy: "Like verifying robot firmware integrity before installation.",
        os_level_explanation: "Performs cryptographic verification of model package integrity.",
        subcommands: &[],
        examples: &["llmverify"],
        see_also: &["llmhash", "llmsig", "llmkey"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmhash",
        category: Category::Llm,
        brief: "Compute model hash",
        what_it_does: "Computes SHA-256 hash of model for verification.",
        use_case: "Use to generate or verify model integrity hashes.",
        functionality: "Calculates SHA-256 hash of model binary.",
        robotics_analogy: "Like computing a checksum for robot firmware to detect corruption.",
        os_level_explanation: "Computes SHA-256 hash for model integrity checking.",
        subcommands: &[],
        examples: &["llmhash 1", "llmhash 1 1024000"],
        see_also: &["llmverify", "llmsig"],
        feature: Some("llm"),
    },

    CommandHelp {
        name: "llmkey",
        category: Category::Llm,
        brief: "Show Ed25519 public key",
        what_it_does: "Displays build-time Ed25519 public key for signature verification.",
        use_case: "Use to view the public key used for model signature verification.",
        functionality: "Shows Ed25519 public key embedded at build time.",
        robotics_analogy: "Like viewing the public key used to verify robot firmware signatures.",
        os_level_explanation: "Displays embedded Ed25519 public key from crypto-real feature.",
        subcommands: &[],
        examples: &["llmkey"],
        see_also: &["llmverify", "llmsig"],
        feature: Some("llm"),
    },

    // ========================================================================
    // CHAOS ENGINEERING (1 command)
    // ========================================================================

    CommandHelp {
        name: "chaos",
        category: Category::ChaosEngineering,
        brief: "Chaos engineering control",
        what_it_does: "Controls chaos engineering fault injection for resilience testing.",
        use_case: "Use to test system resilience by injecting controlled failures.",
        functionality: "Enables fault injection with configurable failure rates and modes.",
        robotics_analogy: "Like deliberately introducing sensor glitches to test if a robot can handle errors gracefully.",
        os_level_explanation: "Phase 4 chaos engineering subsystem for resilience testing with controlled fault injection.",
        subcommands: &[],
        examples: &["chaos mode syscall", "chaos rate 10", "chaos stats"],
        see_also: &["stresstest", "validate"],
        feature: Some("chaos"),
    },

    // ========================================================================
    // OBSERVABILITY (9 commands)
    // ========================================================================

    CommandHelp {
        name: "metricsctl",
        category: Category::Observability,
        brief: "Runtime metric capture control",
        what_it_does: "Controls real-time metrics collection for performance monitoring.",
        use_case: "Use to enable metrics collection for monitoring and optimization.",
        functionality: "Enables/disables runtime metrics capture with low overhead.",
        robotics_analogy: "Like enabling a robot's performance monitoring to track efficiency.",
        os_level_explanation: "Phase 4 metrics subsystem control for runtime performance tracking.",
        subcommands: &[],
        examples: &["metricsctl on", "metricsctl status"],
        see_also: &["metrics", "perf"],
        feature: None,
    },

    CommandHelp {
        name: "metrics",
        category: Category::Observability,
        brief: "Show recent metrics",
        what_it_does: "Displays collected metrics in various formats (JSON, Prometheus, simple).",
        use_case: "Use to view system metrics for analysis or export to monitoring tools.",
        functionality: "Outputs metrics in human-readable, JSON, or Prometheus format.",
        robotics_analogy: "Like reading a robot's performance dashboard showing all sensor and actuator metrics.",
        os_level_explanation: "Phase 4 metrics export supporting multiple formats for monitoring integration.",
        subcommands: &[],
        examples: &["metrics", "metrics json", "metrics prometheus"],
        see_also: &["metricsctl", "perf"],
        feature: None,
    },

    CommandHelp {
        name: "pmu",
        category: Category::Observability,
        brief: "Performance monitoring unit",
        what_it_does: "Controls and displays ARM PMU performance counters.",
        use_case: "Use to measure CPU cycles, instructions, and cache performance.",
        functionality: "Configures and reads ARM PMU hardware performance counters.",
        robotics_analogy: "Like reading a robot's processor performance counters to optimize algorithms.",
        os_level_explanation: "ARM PMU driver for hardware performance counter access.",
        subcommands: &[],
        examples: &["pmu stats"],
        see_also: &["perf", "bench"],
        feature: None,
    },

    CommandHelp {
        name: "perf",
        category: Category::Observability,
        brief: "Performance metrics report",
        what_it_does: "Shows comprehensive performance metrics and statistics.",
        use_case: "Use to analyze system performance and identify bottlenecks.",
        functionality: "Aggregates and displays performance data from various subsystems.",
        robotics_analogy: "Like a robot's performance report showing efficiency across all systems.",
        os_level_explanation: "Performance reporting subsystem aggregating kernel metrics.",
        subcommands: &[],
        examples: &["perf"],
        see_also: &["metrics", "bench"],
        feature: None,
    },

    CommandHelp {
        name: "profstart",
        category: Category::Observability,
        brief: "Start profiler",
        what_it_does: "Starts sampling-based profiler for CPU hotspot analysis.",
        use_case: "Use to identify performance bottlenecks in kernel code.",
        functionality: "Enables timer-based sampling profiler recording call stacks.",
        robotics_analogy: "Like starting a stopwatch on each robot subsystem to see which takes the most time.",
        os_level_explanation: "Sampling profiler using timer interrupts to capture PC histograms.",
        subcommands: &[],
        examples: &["profstart"],
        see_also: &["profstop", "profreport"],
        feature: Some("profiling"),
    },

    CommandHelp {
        name: "profstop",
        category: Category::Observability,
        brief: "Stop profiler",
        what_it_does: "Stops the sampling profiler and saves collected data.",
        use_case: "Use after profstart to stop profiling and prepare report.",
        functionality: "Disables profiler and finalizes sample collection.",
        robotics_analogy: "Like stopping the stopwatch to analyze which robot subsystems are slowest.",
        os_level_explanation: "Stops sampling profiler and prepares data for analysis.",
        subcommands: &[],
        examples: &["profstop"],
        see_also: &["profstart", "profreport"],
        feature: Some("profiling"),
    },

    CommandHelp {
        name: "profreport",
        category: Category::Observability,
        brief: "Show profiling report",
        what_it_does: "Displays profiling report with hotspot analysis.",
        use_case: "Use to see which functions consume the most CPU time.",
        functionality: "Analyzes profiler samples and shows top CPU consumers.",
        robotics_analogy: "Like seeing a breakdown of where a robot spends most of its processing time.",
        os_level_explanation: "Analyzes PC samples to identify hot functions and code paths.",
        subcommands: &[],
        examples: &["profreport"],
        see_also: &["profstart", "profstop"],
        feature: Some("profiling"),
    },

    CommandHelp {
        name: "bench",
        category: Category::Observability,
        brief: "Run performance benchmarks",
        what_it_does: "Executes syscall performance benchmarks.",
        use_case: "Use to measure syscall overhead and kernel performance.",
        functionality: "Runs standardized benchmarks measuring syscall latency.",
        robotics_analogy: "Like running standardized tests to measure a robot's response times.",
        os_level_explanation: "Benchmark suite measuring syscall performance and overhead.",
        subcommands: &[],
        examples: &["bench"],
        see_also: &["overhead", "perf"],
        feature: None,
    },

    CommandHelp {
        name: "overhead",
        category: Category::Observability,
        brief: "Measure syscall overhead",
        what_it_does: "Measures and reports syscall overhead statistics.",
        use_case: "Use to quantify kernel syscall costs for optimization.",
        functionality: "Measures minimum, maximum, and average syscall latency.",
        robotics_analogy: "Like measuring the overhead of asking a robot to do simple tasks.",
        os_level_explanation: "Syscall overhead measurement using high-resolution timers.",
        subcommands: &[],
        examples: &["overhead"],
        see_also: &["bench", "perf"],
        feature: None,
    },

    // ========================================================================
    // CONTROL PLANE (5 commands)
    // ========================================================================

    CommandHelp {
        name: "ctlkey",
        category: Category::ControlPlane,
        brief: "Control plane key management",
        what_it_does: "Shows or rotates control plane cryptographic key.",
        use_case: "Use to manage control plane security credentials.",
        functionality: "Displays current key or rotates to new random key.",
        robotics_analogy: "Like changing the master password for robot fleet control.",
        os_level_explanation: "Control plane key rotation for secure command authentication.",
        subcommands: &[],
        examples: &["ctlkey", "ctlkey 0x1234567890ABCDEF"],
        see_also: &["ctladmin", "ctlsubmit"],
        feature: None,
    },

    CommandHelp {
        name: "ctladmin",
        category: Category::ControlPlane,
        brief: "Show/rotate admin token",
        what_it_does: "Manages admin-level authentication tokens.",
        use_case: "Use to view or update administrative credentials.",
        functionality: "Displays or rotates admin authentication token.",
        robotics_analogy: "Like managing admin access credentials for robot configuration.",
        os_level_explanation: "Admin token management for privileged operations.",
        subcommands: &[],
        examples: &["ctladmin", "ctladmin 0xABCD"],
        see_also: &["ctlkey", "ctlsubmit"],
        feature: None,
    },

    CommandHelp {
        name: "ctlsubmit",
        category: Category::ControlPlane,
        brief: "Show/rotate submit token",
        what_it_does: "Manages submission authentication tokens.",
        use_case: "Use to control access to command submission.",
        functionality: "Displays or rotates submission token.",
        robotics_analogy: "Like managing operator credentials for robot command submission.",
        os_level_explanation: "Submit token management for command authentication.",
        subcommands: &[],
        examples: &["ctlsubmit", "ctlsubmit 0x5678"],
        see_also: &["ctlkey", "ctladmin"],
        feature: None,
    },

    CommandHelp {
        name: "ctlembed",
        category: Category::ControlPlane,
        brief: "Print embedded-rights token",
        what_it_does: "Displays embedded authentication tokens.",
        use_case: "Use to view build-time embedded tokens for testing.",
        functionality: "Shows embedded admin or submit tokens.",
        robotics_analogy: "Like viewing factory-programmed authentication codes.",
        os_level_explanation: "Displays compile-time embedded authentication tokens.",
        subcommands: &[],
        examples: &["ctlembed admin", "ctlembed submit"],
        see_also: &["ctladmin", "ctlsubmit"],
        feature: None,
    },

    CommandHelp {
        name: "ctlhex",
        category: Category::ControlPlane,
        brief: "Inject control frame as hex",
        what_it_does: "Injects binary control frames for graph control.",
        use_case: "Use for low-level graph control frame injection.",
        functionality: "Parses hex strings as control frames for graph subsystem.",
        robotics_analogy: "Like sending raw binary commands to a robot's low-level controller.",
        os_level_explanation: "Low-level control frame injection for graph pipeline testing.",
        subcommands: &[],
        examples: &["ctlhex 010203..."],
        see_also: &["graphctl"],
        feature: None,
    },

    // ========================================================================
    // DETERMINISTIC (2 commands)
    // ========================================================================

    CommandHelp {
        name: "det",
        category: Category::Deterministic,
        brief: "Deterministic scheduling control",
        what_it_does: "Controls deterministic real-time scheduling with WCET constraints.",
        use_case: "Use to enable hard real-time guarantees for critical tasks.",
        functionality: "Configures CBS (Constant Bandwidth Server) with WCET/period/deadline.",
        robotics_analogy: "Like setting strict timing requirements for robot control loops that must never be missed.",
        os_level_explanation: "Deterministic scheduler using CBS for guaranteed real-time execution.",
        subcommands: &[],
        examples: &["det on 1000000 10000000 10000000", "det status"],
        see_also: &["graphctl det", "schedctl"],
        feature: Some("deterministic"),
    },

    CommandHelp {
        name: "graphctl",
        category: Category::Deterministic,
        brief: "Control graph pipeline",
        what_it_does: "Manages dataflow graph for deterministic AI pipelines.",
        use_case: "Use to build and execute deterministic AI processing graphs.",
        functionality: "Creates graphs with channels and operators for deterministic execution.",
        robotics_analogy: "Like connecting robot sensor processing modules in a pipeline with guaranteed timing.",
        os_level_explanation: "Dataflow graph subsystem for deterministic AI pipeline execution.",
        subcommands: &[],
        examples: &["graphctl create", "graphctl add-channel 10", "graphctl start 100"],
        see_also: &["det", "llmgraph"],
        feature: None,
    },

    // ========================================================================
    // HARDWARE (3 commands)
    // ========================================================================

    CommandHelp {
        name: "gpio",
        category: Category::Hardware,
        brief: "GPIO control",
        what_it_does: "Controls GPIO pins for hardware interfacing.",
        use_case: "Use to control digital I/O pins for external hardware.",
        functionality: "Set, clear, toggle, read GPIO pins with direction control.",
        robotics_analogy: "Like controlling robot actuators or reading sensors through digital I/O pins.",
        os_level_explanation: "GPIO driver for digital pin control and sensing.",
        subcommands: &[],
        examples: &["gpio set 17", "gpio read 27", "gpio blink 4 500"],
        see_also: &["mailbox", "selftest"],
        feature: None,
    },

    CommandHelp {
        name: "mailbox",
        category: Category::Hardware,
        brief: "Firmware mailbox interface",
        what_it_does: "Communicates with firmware via mailbox interface.",
        use_case: "Use to query system information from firmware (temperature, serial, etc).",
        functionality: "Sends mailbox requests to firmware for system information.",
        robotics_analogy: "Like querying a robot's embedded controller for hardware status.",
        os_level_explanation: "Mailbox interface for firmware communication and system queries.",
        subcommands: &[],
        examples: &["mailbox serial", "mailbox all"],
        see_also: &["gpio", "board"],
        feature: None,
    },

    CommandHelp {
        name: "vconwrite",
        category: Category::Hardware,
        brief: "VirtIO console write",
        what_it_does: "Sends text to host via VirtIO console.",
        use_case: "Use to send data from guest to host for debugging or logging.",
        functionality: "Writes text through VirtIO console to host system.",
        robotics_analogy: "Like a robot sending telemetry data back to a base station.",
        os_level_explanation: "VirtIO console driver for guest-to-host communication.",
        subcommands: &[],
        examples: &["vconwrite Hello from kernel"],
        see_also: &[],
        feature: Some("virtio-console"),
    },

    // ========================================================================
    // LOGGING & VALIDATION (3 commands)
    // ========================================================================

    CommandHelp {
        name: "logctl",
        category: Category::LoggingValidation,
        brief: "Logging control",
        what_it_does: "Controls logging system level and output format.",
        use_case: "Use to adjust log verbosity or switch between human/JSON formats.",
        functionality: "Sets log level and output format (development/production/testing).",
        robotics_analogy: "Like adjusting a robot's logging verbosity for debugging vs production.",
        os_level_explanation: "Logging subsystem control for level and format configuration.",
        subcommands: &[],
        examples: &["logctl status", "logctl level DEBUG", "logctl demo"],
        see_also: &["validate"],
        feature: None,
    },

    CommandHelp {
        name: "validate",
        category: Category::LoggingValidation,
        brief: "Production validation suite",
        what_it_does: "Runs comprehensive validation test suites.",
        use_case: "Use to verify system correctness before deployment.",
        functionality: "Executes validation tests covering stress, performance, and integration.",
        robotics_analogy: "Like running a robot through acceptance tests before shipping.",
        os_level_explanation: "Phase 4 validation framework with multiple test categories.",
        subcommands: &[],
        examples: &["validate all", "validate quick", "validate stress"],
        see_also: &["selftest", "verify"],
        feature: None,
    },

    CommandHelp {
        name: "selftest",
        category: Category::LoggingValidation,
        brief: "Driver self-tests",
        what_it_does: "Runs driver self-test suites for hardware validation.",
        use_case: "Use to verify driver functionality and hardware operation.",
        functionality: "Executes built-in self-tests for drivers (GPIO, mailbox, PMU).",
        robotics_analogy: "Like testing each robot subsystem independently to ensure it works.",
        os_level_explanation: "Phase 4 driver self-test framework for hardware validation.",
        subcommands: &[],
        examples: &["selftest all", "selftest gpio", "selftest pmu"],
        see_also: &["validate", "gpio", "pmu"],
        feature: None,
    },

    // ========================================================================
    // STRESS TESTING (3 commands)
    // ========================================================================

    CommandHelp {
        name: "stress",
        category: Category::StressTesting,
        brief: "Run syscall stress tests",
        what_it_does: "Executes intensive syscall stress testing.",
        use_case: "Use to verify kernel stability under heavy load.",
        functionality: "Generates high syscall load to stress test kernel paths.",
        robotics_analogy: "Like running a robot at maximum capacity to ensure it doesn't fail.",
        os_level_explanation: "Syscall stress test generating high kernel load.",
        subcommands: &[],
        examples: &["stress"],
        see_also: &["stresstest", "bench"],
        feature: None,
    },

    CommandHelp {
        name: "stresstest",
        category: Category::StressTesting,
        brief: "Advanced stress testing",
        what_it_does: "Runs advanced stress tests for various subsystems.",
        use_case: "Use to test system resilience under different stress scenarios.",
        functionality: "Executes memory, command, multi-agent, learning, redteam, and chaos tests.",
        robotics_analogy: "Like putting a robot through various challenging scenarios to test limits.",
        os_level_explanation: "Comprehensive stress test framework with multiple test modes.",
        subcommands: &[],
        examples: &["stresstest memory", "stresstest learning --duration 5000"],
        see_also: &["stress", "chaos", "validate"],
        feature: None,
    },

    CommandHelp {
        name: "benchmark",
        category: Category::StressTesting,
        brief: "System benchmarks",
        what_it_does: "Runs comprehensive system benchmarks.",
        use_case: "Use to measure system performance across multiple dimensions.",
        functionality: "Benchmarks memory, commands, network, and generates performance reports.",
        robotics_analogy: "Like running standardized tests to measure a robot's performance across all systems.",
        os_level_explanation: "Benchmark suite measuring system performance with standardized workloads.",
        subcommands: &[],
        examples: &["benchmark memory", "benchmark full", "benchmark report"],
        see_also: &["bench", "perf", "stresstest"],
        feature: None,
    },

    // ========================================================================
    // COMPLIANCE (1 command)
    // ========================================================================

    CommandHelp {
        name: "compliance",
        category: Category::Compliance,
        brief: "Compliance reporting",
        what_it_does: "Generates compliance reports for regulatory requirements.",
        use_case: "Use to generate EU AI Act compliance reports and audit trails.",
        functionality: "Produces compliance reports, audit logs, transparency docs, and incident tracking.",
        robotics_analogy: "Like generating regulatory compliance documentation for robot deployment.",
        os_level_explanation: "Compliance reporting system for AI governance and regulatory requirements.",
        subcommands: &[],
        examples: &["compliance eu-ai-act", "compliance audit", "compliance transparency"],
        see_also: &["agentsys compliance", "llmjson"],
        feature: None,
    },

    // ========================================================================
    // DEVELOPMENT (4 commands)
    // ========================================================================

    CommandHelp {
        name: "test",
        category: Category::Development,
        brief: "Run syscall tests",
        what_it_does: "Executes basic syscall functionality tests.",
        use_case: "Use to verify syscall implementation correctness.",
        functionality: "Runs test suite covering core syscalls.",
        robotics_analogy: "Like testing individual robot functions to ensure they work correctly.",
        os_level_explanation: "Basic syscall test suite for functionality verification.",
        subcommands: &[],
        examples: &["test"],
        see_also: &["verify", "validate"],
        feature: None,
    },

    CommandHelp {
        name: "perf_test",
        category: Category::Development,
        brief: "Performance optimization tests",
        what_it_does: "Runs performance optimization tests for various architectures.",
        use_case: "Use to verify performance optimizations and architecture-specific code.",
        functionality: "Tests RISC-V and ARM performance optimizations.",
        robotics_analogy: "Like testing if robot performance optimizations actually improve speed.",
        os_level_explanation: "Architecture-specific performance test suite.",
        subcommands: &[],
        examples: &["perf_test"],
        see_also: &["bench", "perf"],
        feature: None,
    },

    CommandHelp {
        name: "ai_bench",
        category: Category::Development,
        brief: "AI/ML benchmarks",
        what_it_does: "Runs AI and ML performance benchmarks.",
        use_case: "Use to measure AI subsystem performance.",
        functionality: "Benchmarks neural network inference and learning performance.",
        robotics_analogy: "Like measuring how fast a robot's AI can make decisions.",
        os_level_explanation: "AI/ML benchmark suite for performance measurement.",
        subcommands: &[],
        examples: &["ai_bench"],
        see_also: &["bench", "neuralctl"],
        feature: None,
    },

    CommandHelp {
        name: "rtaivalidation",
        category: Category::Development,
        brief: "Real-time AI validation",
        what_it_does: "Runs comprehensive real-time AI inference validation.",
        use_case: "Use to verify real-time AI guarantees and timing constraints.",
        functionality: "Validates AI inference meets real-time deadlines.",
        robotics_analogy: "Like verifying a robot's AI can make decisions within strict time limits.",
        os_level_explanation: "Real-time AI validation ensuring deterministic inference timing.",
        subcommands: &[],
        examples: &["rtaivalidation"],
        see_also: &["det", "validate"],
        feature: None,
    },

    // ========================================================================
    // DEMOS (17 commands)
    // ========================================================================

    CommandHelp {
        name: "graphdemo",
        category: Category::Demos,
        brief: "Run graph demo",
        what_it_does: "Demonstrates dataflow graph functionality.",
        use_case: "Use to see graph-based processing in action.",
        functionality: "Runs example graph pipeline with channels and operators.",
        robotics_analogy: "Like a demo of robot sensor data flowing through processing stages.",
        os_level_explanation: "Graph subsystem demonstration.",
        subcommands: &[],
        examples: &["graphdemo"],
        see_also: &["graphctl"],
        feature: Some("graph-demo"),
    },

    CommandHelp {
        name: "imagedemo",
        category: Category::Demos,
        brief: "Image classification demo",
        what_it_does: "Demonstrates image classification (simulated).",
        use_case: "Use to see AI image processing example.",
        functionality: "Simulates image-to-labels classification.",
        robotics_analogy: "Like a robot identifying objects in its camera view.",
        os_level_explanation: "Simulated image classification demo.",
        subcommands: &[],
        examples: &["imagedemo"],
        see_also: &["mldemo", "infdemo"],
        feature: None,
    },

    CommandHelp {
        name: "detdemo",
        category: Category::Demos,
        brief: "Deterministic scheduler demo",
        what_it_does: "Demonstrates deterministic scheduling.",
        use_case: "Use to see real-time scheduling in action.",
        functionality: "Shows CBS-based deterministic task execution.",
        robotics_analogy: "Like demonstrating guaranteed-timing robot control loops.",
        os_level_explanation: "Deterministic scheduler demonstration.",
        subcommands: &[],
        examples: &["detdemo"],
        see_also: &["det"],
        feature: Some("deterministic"),
    },

    CommandHelp {
        name: "aidemo",
        category: Category::Demos,
        brief: "AI-enhanced scheduler demo",
        what_it_does: "Demonstrates AI-driven scheduling optimization.",
        use_case: "Use to see AI improving scheduling decisions.",
        functionality: "Shows neural scheduler making intelligent priority decisions.",
        robotics_analogy: "Like watching a robot learn optimal task ordering.",
        os_level_explanation: "AI-enhanced scheduler demonstration.",
        subcommands: &[],
        examples: &["aidemo"],
        see_also: &["schedctl", "neuralctl"],
        feature: None,
    },

    CommandHelp {
        name: "cbsdemo",
        category: Category::Demos,
        brief: "CBS+EDF budget demo",
        what_it_does: "Demonstrates CBS budget management for AI inference.",
        use_case: "Use to see real-time budget enforcement in action.",
        functionality: "Shows CBS managing AI inference within time budgets.",
        robotics_analogy: "Like demonstrating time-budget enforcement for robot AI thinking.",
        os_level_explanation: "CBS+EDF demonstration for deterministic AI.",
        subcommands: &[],
        examples: &["cbsdemo"],
        see_also: &["det", "infdemo"],
        feature: None,
    },

    CommandHelp {
        name: "mldemo",
        category: Category::Demos,
        brief: "TinyML demo",
        what_it_does: "Demonstrates Phase 3 TinyML inference.",
        use_case: "Use to see on-device ML inference.",
        functionality: "Runs TinyML inference example.",
        robotics_analogy: "Like demonstrating a robot running AI models locally.",
        os_level_explanation: "Phase 3 TinyML demonstration.",
        subcommands: &[],
        examples: &["mldemo"],
        see_also: &["infdemo", "imagedemo"],
        feature: None,
    },

    CommandHelp {
        name: "infdemo",
        category: Category::Demos,
        brief: "Deterministic inference demo",
        what_it_does: "Demonstrates cycle-accurate deterministic inference.",
        use_case: "Use to see guaranteed-timing AI inference.",
        functionality: "Shows deterministic neural network inference.",
        robotics_analogy: "Like demonstrating a robot AI that always finishes thinking in exact time.",
        os_level_explanation: "Deterministic inference demonstration with cycle accuracy.",
        subcommands: &[],
        examples: &["infdemo"],
        see_also: &["det", "mldemo"],
        feature: None,
    },

    CommandHelp {
        name: "npudemo",
        category: Category::Demos,
        brief: "NPU device emulation demo",
        what_it_does: "Demonstrates NPU device emulation with MMIO/IRQ.",
        use_case: "Use to see NPU device driver interaction.",
        functionality: "Emulates NPU with memory-mapped I/O and interrupts.",
        robotics_analogy: "Like demonstrating a robot's AI accelerator hardware.",
        os_level_explanation: "NPU device emulation demo with MMIO and interrupt handling.",
        subcommands: &[],
        examples: &["npudemo"],
        see_also: &["npudriver"],
        feature: None,
    },

    CommandHelp {
        name: "npudriver",
        category: Category::Demos,
        brief: "NPU driver demo",
        what_it_does: "Demonstrates NPU driver with interrupt handling.",
        use_case: "Use to see NPU driver functionality.",
        functionality: "Shows NPU driver managing hardware interrupts.",
        robotics_analogy: "Like demonstrating how a robot's AI chip driver works.",
        os_level_explanation: "NPU driver demonstration with IRQ handling.",
        subcommands: &[],
        examples: &["npudriver"],
        see_also: &["npudemo"],
        feature: None,
    },

    CommandHelp {
        name: "coorddemo",
        category: Category::Demos,
        brief: "Cross-agent coordination demo",
        what_it_does: "Demonstrates multi-agent coordination under stress.",
        use_case: "Use to see agents cooperating and resolving conflicts.",
        functionality: "Shows coordctl managing multiple agents.",
        robotics_analogy: "Like watching multiple robots work together without colliding.",
        os_level_explanation: "Phase 2 coordination demonstration.",
        subcommands: &[],
        examples: &["coorddemo"],
        see_also: &["coordctl"],
        feature: None,
    },

    CommandHelp {
        name: "metademo",
        category: Category::Demos,
        brief: "Meta-agent demo",
        what_it_does: "Demonstrates meta-agent with multi-subsystem stress.",
        use_case: "Use to see hierarchical agent control.",
        functionality: "Shows meta-agent coordinating other agents.",
        robotics_analogy: "Like a supervisor robot managing worker robots.",
        os_level_explanation: "Phase 2 meta-agent demonstration.",
        subcommands: &[],
        examples: &["metademo"],
        see_also: &["metaclassctl"],
        feature: None,
    },

    CommandHelp {
        name: "mladvdemo",
        category: Category::Demos,
        brief: "Advanced ML features demo",
        what_it_does: "Demonstrates experience replay, TD learning, and topology adaptation.",
        use_case: "Use to see advanced learning algorithms in action.",
        functionality: "Shows mlctl advanced features.",
        robotics_analogy: "Like watching a robot learn from past experiences and predict future states.",
        os_level_explanation: "Phase 2 advanced ML demonstration.",
        subcommands: &[],
        examples: &["mladvdemo"],
        see_also: &["mlctl"],
        feature: None,
    },

    CommandHelp {
        name: "actorcriticdemo",
        category: Category::Demos,
        brief: "Actor-critic demo",
        what_it_does: "Demonstrates actor-critic with policy gradients.",
        use_case: "Use to see reinforcement learning with actor-critic architecture.",
        functionality: "Shows actorctl with eligibility traces.",
        robotics_analogy: "Like watching a robot learn actions while a critic evaluates performance.",
        os_level_explanation: "Phase 2 actor-critic RL demonstration.",
        subcommands: &[],
        examples: &["actorcriticdemo"],
        see_also: &["actorctl"],
        feature: None,
    },

    CommandHelp {
        name: "temporaliso",
        category: Category::Demos,
        brief: "AI temporal isolation demo",
        what_it_does: "Demonstrates temporal isolation for AI inference.",
        use_case: "Use to see how AI tasks are isolated in time.",
        functionality: "Shows temporal isolation preventing interference.",
        robotics_analogy: "Like ensuring one robot task doesn't interfere with another's timing.",
        os_level_explanation: "Temporal isolation demonstration for AI workloads.",
        subcommands: &[],
        examples: &["temporaliso"],
        see_also: &["det", "rtaivalidation"],
        feature: None,
    },

    CommandHelp {
        name: "phase3validation",
        category: Category::Demos,
        brief: "Phase 3 validation suite",
        what_it_does: "Runs complete Phase 3 AI-native kernel validation.",
        use_case: "Use to validate full Phase 3 implementation.",
        functionality: "Comprehensive Phase 3 test suite.",
        robotics_analogy: "Like running full acceptance tests for robot AI system.",
        os_level_explanation: "Phase 3 comprehensive validation suite.",
        subcommands: &[],
        examples: &["phase3validation"],
        see_also: &["rtaivalidation", "validate"],
        feature: None,
    },

    CommandHelp {
        name: "fullautodemo",
        category: Category::Demos,
        brief: "Full autonomous system demo",
        what_it_does: "Demonstrates complete autonomous system operation.",
        use_case: "Use to see all autonomous features working together.",
        functionality: "Runs comprehensive autonomous system demo.",
        robotics_analogy: "Like watching a fully autonomous robot operate without human intervention.",
        os_level_explanation: "Comprehensive autonomous system demonstration.",
        subcommands: &[],
        examples: &["fullautodemo"],
        see_also: &["autoctl", "coorddemo"],
        feature: None,
    },
];
